inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

mypy:
  options:
    python-version: '3.9'

ruff:
  disable:
    - PTH # pathlib
  options:
    target-version: py39

pycodestyle:
  disable:
    - E704 # multiple statements on one line (def) (not compatible with protocol)
