inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

pycodestyle:
  disable:
    - E704 # multiple statements on one line (def) (not compatible with protocol)

ruff:
  disable:
    - PTH # pathlib
