inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

mypy:
  options:
    python-version: '3.9'

ruff:
  disable:
    - D101 # Missing docstring in public class
    - D102 # Missing docstring in public method
    - D103 # Missing docstring in public function
    - PTH # pathlib
    - PERF # Performance
    - ANN # Type annotations
  options:
    target-version: py39

pycodestyle:
  disable:
    - E704 # multiple statements on one line (def) (not compatible with protocol)
