[tool.black]
line-length = 110
target-version = ["py39"]

[mypy]
python_version = 3.9
warn_redundant_casts = true
warn_unused_ignores = true
ignore_missing_imports = true
strict_optional = true
strict = true

[tool.poetry]
name = "c2c.template"
version = "0.0.0"
description = "Vars collector and template runner."
readme = "README.rst"
authors = ["Camptocamp <info@camptocamp.com>"]
repository = "https://github.com/camptocamp/c2c.template"
license = "BSD-2-Clause"
keywords = ["template"]
packages = [{ include = "c2c/template" }]
classifiers = [
    "Programming Language :: Python",
    "Environment :: Console",
    "Framework :: Bottle",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
include = ["c2c/template/py.typed"]

[tool.poetry.scripts]
c2c-template = "c2c.template:main"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
bottle = "0.12.25"
Jinja2 = "3.1.4"
Mako = "1.3.5"
PyYAML = "6.0.2"
pyyaml-include = "2.1"

[tool.poetry.group.dev.dependencies]
prospector = { version = "1.10.3", extras = ["with_bandit", "with_mypy", "with_pyroma"] }
prospector-profile-duplicated = "1.5.0"
prospector-profile-utils = "1.7.2"
pytest = "8.3.2"
types-PyYAML = "6.0.12.20240808"



[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning", "poetry-plugin-tweak-dependencies-version", "poetry-plugin-drop-python-upper-constraint"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "^((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)"
format-jinja = """
{%- if env.get("VERSION_TYPE") == "version_branch" -%}
{{serialize_pep440(bump_version(base, 1 if env.get("IS_MASTER") == "TRUE" else 2), dev=distance)}}
{%- elif distance == 0 -%}
{{serialize_pep440(base)}}
{%- else -%}
{{serialize_pep440(bump_version(base), dev=distance)}}
{%- endif -%}
"""

[tool.poetry-plugin-tweak-dependencies-version]
default = "present"
pyyaml-include = ">=2.0"
