[tool.black]
line-length = 110
target-version = ["py39"]

[mypy]
python_version = 3.9
warn_redundant_casts = true
warn_unused_ignores = true
ignore_missing_imports = true
strict_optional = true
strict = true

[tool.poetry]
name = "c2c.template"
version = "0.0.0"
description = "Vars collector and template runner."
readme = "README.rst"
authors = ["Camptocamp <info@camptocamp.com>"]
repository = "https://github.com/camptocamp/c2c.template"
license = "BSD-2-Clause"
keywords = ["template"]
packages = [{ include = "c2c" }]
classifiers = [
    "Programming Language :: Python",
    "Environment :: Console",
    "Framework :: Bottle",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
include = ["tilecloud_chain/py.typed"]

[tool.poetry.scripts]
c2c-template = "c2c.template:main"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
bottle = "0.12.25"
Jinja2 = "3.1.2"
Mako = "1.2.4"
PyYAML = "6.0.1"
pyyaml-include = "1.3.1"

[tool.poetry.dev-dependencies]
prospector = { version = "1.10.2", extras = ["with_bandit", "with_mypy", "with_pyroma"] }
pylint = "2.17.7"
pytest = "7.4.2"
types-PyYAML = "6.0.12.12"

[tool.poetry.group.dev.dependencies]
prospector-profile-duplicated = "0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning", "poetry-plugin-tweak-dependencies-version"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "^((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)"

[tool.poetry-plugin-tweak-dependencies-version]
default = "present"
