checks:
    required_workflows:
        clean.yaml: False
        audit.yaml: False
        rebuild.yaml: False
        backport.yaml: False
    versions:
        audit: False
        rebuild: False

publish:
    docker:
        images: []
